name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ secrets.AromalShaji }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      # GitHub Pages Action
      - name: GitHub Pages Action
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPENDABOT_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }} # Add your DEPENDABOT_TOKEN secret here

# Define permissions
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
